### ISSUE TITLE
Self compiled doesn't work.

### ISSUE THREAD

**Issue by antonyip** [wombatt/BurstWallet#8]
node.js v7.7.3
windows 10
64-bit

$ npm install 
$ npm run pack
$ npm run rename

[https://www.dropbox.com/s/kw8jvh1jm51mhyg/NothingAppears.PNG?dl=0](https://www.dropbox.com/s/kw8jvh1jm51mhyg/NothingAppears.PNG?dl=0)

downloaded wallet works tho.

**Comment by az-rr** [comment]
Run `electron .` in the root folder. You will get a debug log there. You will more than likely need to compile 'diskusage' for electron too. see [here](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md)

**Comment by antonyip** [comment]
Sorry for the late reply, Have been busy.

I get this error when trying to instaill diskusage.

418 warn BurstWalletAIO@1.1.0 No license field.
419 verbose If you need help, you may report this error at:
419 verbose     <https://github.com/npm/npm/issues>
420 warn Error: EPERM: operation not permitted, unlink 'C:\Users\AntonWin10\Desktop\BurstWallet-master\node_modules\diskusage\index.d.ts'
420 warn  { Error: EPERM: operation not permitted, unlink 'C:\Users\AntonWin10\Desktop\BurstWallet-master\node_modules\diskusage\index.d.ts'
420 warn   errno: -4048,
420 warn   code: 'EPERM',
420 warn   syscall: 'unlink',
420 warn   path: 'C:\\Users\\AntonWin10\\Desktop\\BurstWallet-master\\node_modules\\diskusage\\index.d.ts' }
421 verbose Please try running this command again as root/Administrator.
422 verbose stack Error: diskusage@0.2.1 install: `node-gyp rebuild`
422 verbose stack Exit status 1
422 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
422 verbose stack     at emitTwo (events.js:106:13)
422 verbose stack     at EventEmitter.emit (events.js:194:7)
422 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
422 verbose stack     at emitTwo (events.js:106:13)
422 verbose stack     at ChildProcess.emit (events.js:194:7)
422 verbose stack     at maybeClose (internal/child_process.js:899:16)
422 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
423 verbose pkgid diskusage@0.2.1
424 verbose cwd C:\Users\AntonWin10\Desktop\BurstWallet-master
425 error Windows_NT 10.0.14393
426 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "diskusage"
427 error node v7.7.3
428 error npm  v4.1.2
429 error code ELIFECYCLE
430 error diskusage@0.2.1 install: `node-gyp rebuild`
430 error Exit status 1
431 error Failed at the diskusage@0.2.1 install script 'node-gyp rebuild'.
431 error Make sure you have the latest version of node.js and npm installed.
431 error If you do, this is most likely a problem with the diskusage package,
431 error not with npm itself.
431 error Tell the author that this fails on your system:
431 error     node-gyp rebuild
431 error You can get information on how to open an issue for this project with:
431 error     npm bugs diskusage
431 error Or if that isn't available, you can get their info via:
431 error     npm owner ls diskusage
431 error There is likely additional logging output above.

attached is full log.
[npm-debug.txt](https://github.com/wombatt/BurstWallet/files/872341/npm-debug.txt)
